client_config_backend: file
client_config:
    client_id: 918458155689-n08m6rl2r73s68l4elv6bjic38kaioi3.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive